"""Initial schema setup

Revision ID: d1e181a4f65f
Revises: 
Create Date: 2026-08-25 01:06:24.474821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e181a4f65f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('original_file_url', sa.String(), nullable=True),
    sa.Column('processed_file_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_jobs_filename'), 'file_jobs', ['filename'], unique=False)
    op.create_index(op.f('ix_file_jobs_id'), 'file_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_file_jobs_task_type'), 'file_jobs', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_jobs_task_type'), table_name='file_jobs')
    op.drop_index(op.f('ix_file_jobs_id'), table_name='file_jobs')
    op.drop_index(op.f('ix_file_jobs_filename'), table_name='file_jobs')
    op.drop_table('file_jobs')
    # ### end Alembic commands ###
